# Generated by Django 5.0.3 on 2024-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group_created_at_group_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='users.group'),
        ),
    ]
