# Generated by Django 5.0.3 on 2024-03-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('id_number', models.IntegerField(db_index=True, unique=True)),
                ('date_of_joining', models.DateField()),
                ('salary', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table_comment': 'This contains Employee data',
            },
        ),
    ]
