# Generated by Django 5.0.3 on 2024-03-26 15:35

import django.db.models.deletion
import test_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_employee_created_at_alter_employee_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('employee_count', models.PositiveBigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=test_app.models.Employee.DESIGNATION.choices, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='test_app.department'),
        ),
    ]
