# Generated by Django 5.0.3 on 2024-03-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_number', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=32)),
                ('manufacturer', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelTableComment(
            name='employee',
            table_comment=None,
        ),
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ManyToManyField(to='test_app.device'),
        ),
    ]
